data:
  path: /tmp/math_Qwen2-7B-Instruct.parquet
  prompt_key: prompt
  response_key: responses
  edit_response_key: edit_responses
  data_source_key: data_source
  reward_model_key: reward_model
  max_response_length: 2048
  n_pass: 8
